name: Main workflow

on:
  - pull_request
  - push

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: corepack enable

      - run: yarn install --immutable

      - run: yarn ci

      - run: yarn build
