name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
      - name: Set-up Node.js
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version-file: .nvmrc
          package-manager-cache: false
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn build
