name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v6
      - name: Set-up Mise
        uses: jdx/mise-action@v4
      - run: bun install --frozen-lockfile
      - run: bun run lint
      - run: bun run build
